### ISSUE TITLE
Multiple failures --- write error might be permanent

### ISSUE THREAD

**Issue by phamduykhuong** [polardb/PolarDB-for-PostgreSQL#166] opened 2021-09-28 04:17 UTC
I setup 5 polardb servers 1 primary (32Cores, 256 GB) + 4 replica ( 32Cores, 256 GB).
Benchmark follow the instructions: https://www.alibabacloud.com/help/doc-detail/116849.htm?spm=a2c63.l28256.a3.43.38cf6593kJamQZ.
when run simultaneously read/write on primary and  read only on replicas, output log have errors on primary: 

DETAIL:  Multiple failures --- write error might be permanent.
WARNING:  page verification failed, calculated checksum 54072 but expected 31072
ERROR:  invalid page in block 781267 of relation file-dio:///data/data_dir_polardb_pg/base/12418/16431
WARNING:  could not write block 781267 of file-dio:///data/data_dir_polardb_pg/base/12418/16431
DETAIL:  Multiple failures --- write error might be permanent.
WARNING:  page verification failed, calculated checksum 443 but expected 27345
ERROR:  invalid page in block 944996 of relation file-dio:///data/data_dir_polardb_pg/base/12418/16431
WARNING:  could not write block 944996 of file-dio:///data/data_dir_polardb_pg/base/12418/16431
DETAIL:  Multiple failures --- write error might be permanent.
WARNING:  page verification failed, calculated checksum 54362 but expected 24252
ERROR:  invalid page in block 702044 of relation file-dio:///data/data_dir_polardb_pg/base/12418/16431
WARNING:  could not write block 702044 of file-dio:///data/data_dir_polardb_pg/base/12418/16431

In case, run only  read/write on primary is normal.
What's issue with primary polardb?

**Comment by guangzhouzhang** [comment] 2021-09-29 08:42
this should be a known issue caused by a RO node reading a  data page partially-written by the RW node. In a standard shared-storage configuration, this issue can be avoided by the atomic-writing feature of the storage layer. In this shared-local-disk configuration, this can be fixed by retry reading page if a page verification failed while reading page.

**Comment by phamduykhuong** [comment] 2021-10-06 15:50
I tested  under many distribute filesystem: gpfs - san backend, gpfs- share nothing, nfs with sync flag. All of them the same.

**Comment by mrdrivingduck** [comment] 2022-05-10 16:03
Since newer version of PolarDB is released, this issue will be closed. If you have the same question on current stable code of PolarDB, please open a new issue. Thanks~

**Closed as completed by mrdrivingduck** 2022-05-10 16:03 UTC
Labels: wontfix
